import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import WelcomeDialog from "@/components/WelcomeDialog";
import Header from "@/components/Header";
import { IsSoundUrlProvider } from "@/components/IsSoundUrlContext";
import LoadingOverlay from "@/components/LoadingOverlay";

const bizGothic = localFont({
  src: "./fonts/BIZUDGothic-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${bizGothic.className} bg-black`}>
        <IsSoundUrlProvider>
          <Header />
          <WelcomeDialog />
          {children}
          <LoadingOverlay />
        </IsSoundUrlProvider>
      </body>
    </html>
  );
}
