import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import ClientCanvasWrapper from "./ClinentCanvasWrapper";

const dotGothic = localFont({
  src: "./fonts/DotGothic16-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dotGothic.className}>
        <section className="w-full h-screen relative bg-white">
          <ClientCanvasWrapper>{children}</ClientCanvasWrapper>
        </section>
      </body>
    </html>
  );
}
