import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import RadioStationHomepage from "./NewPage";

const bizGothic = localFont({
  src: "./fonts/BIZUDGothic-Regular.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={bizGothic.className}>
        <RadioStationHomepage />
      </body>
    </html>
  );
}
